/******************************************************************************/
/***               Generated by IBExpert 27.05.2025 13:12:07                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR G_FILES;

CREATE TABLE FILES (
    ID           INTEGER,
    CUSTNO       INTEGER,
    FOLDER_ID    INTEGER,
    FILE_NAME    VARCHAR(255),
    FILE_BODY    BLOB SUB_TYPE 0 SEGMENT SIZE 80,
    FILE_SIZE    BIGINT,
    USER_CHANGE  INTEGER,
    TIME_CHANGE  TIMESTAMP,
    FOLDER       VARCHAR(1)
);



/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE INDEX FILES_ID ON FILES (ID);
CREATE INDEX FILES_IDX1 ON FILES (CUSTNO);
CREATE INDEX FILES_IDX2 ON FILES (FOLDER_ID);
CREATE INDEX FILES_IDX3 ON FILES (FOLDER);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: BI_FILES */
CREATE OR ALTER TRIGGER BI_FILES FOR FILES
ACTIVE BEFORE INSERT POSITION 0
AS 
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(G_FILES, 1); 
END
^
SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/
